# Generated by Django 2.2.6 on 2020-02-03 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='工单号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.CharField(choices=[('0', '初次安装'), ('1', '售后现场'), ('2', '远程支持'), ('3', '售前支持')], max_length=10)),
                ('status', models.CharField(choices=[('0', '工单已退回'), ('1', '新建-保存'), ('2', '提交-等待审批'), ('3', '已审批-等待执行'), ('4', '已执行-等待确认'), ('5', '工单已完成')], max_length=10)),
                ('do_time', models.DateTimeField(default='', verbose_name='安排时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(max_length=300, verbose_name='工单内容')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='项目资料')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposer', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='接单人')),
            ],
            options={
                'verbose_name': '工单信息',
                'verbose_name_plural': '工单信息',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('0', '退回'), ('1', '派发'), ('2', '执行'), ('3', '确认')], max_length=10, verbose_name='记录类型')),
                ('content', models.CharField(default='', max_length=500, verbose_name='记录内容')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='实施文档')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='工单信息')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
            },
        ),
    ]
